export const SELECT_TICKER = 'SELECT_TICKER';

export const REQUEST_STOCKLIST = 'REQUEST_STOCKLIST';
export const RECEIVE_STOCKLIST = 'RECEIVE_STOCKLIST';
export const RECEIVE_STOCKLIST_ERROR = 'RECEIVE_STOCKLIST_ERROR';

export const REQUEST_HISTORICAL_PRICES = 'REQUEST_HISTORICAL_PRICES';
export const RECEIVE_HISTORICAL_PRICES = 'RECEIVE_HISTORICAL_PRICES';
export const RECEIVE_HISTORICAL_PRICES_ERROR = 'RECEIVE_HISTORICAL_PRICES_ERROR';